/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookInputRouteImport } from './routes/book-input'
import { Route as BookBorrowingRouteImport } from './routes/book-borrowing'
import { Route as AccessControlRouteImport } from './routes/access-control'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookInputRoute = BookInputRouteImport.update({
  id: '/book-input',
  path: '/book-input',
  getParentRoute: () => rootRouteImport,
} as any)
const BookBorrowingRoute = BookBorrowingRouteImport.update({
  id: '/book-borrowing',
  path: '/book-borrowing',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessControlRoute = AccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/book-borrowing': typeof BookBorrowingRoute
  '/book-input': typeof BookInputRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/book-borrowing': typeof BookBorrowingRoute
  '/book-input': typeof BookInputRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/book-borrowing': typeof BookBorrowingRoute
  '/book-input': typeof BookInputRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-control'
    | '/book-borrowing'
    | '/book-input'
    | '/dashboard'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-control'
    | '/book-borrowing'
    | '/book-input'
    | '/dashboard'
    | '/login'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/access-control'
    | '/book-borrowing'
    | '/book-input'
    | '/dashboard'
    | '/login'
    | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessControlRoute: typeof AccessControlRoute
  BookBorrowingRoute: typeof BookBorrowingRoute
  BookInputRoute: typeof BookInputRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-input': {
      id: '/book-input'
      path: '/book-input'
      fullPath: '/book-input'
      preLoaderRoute: typeof BookInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-borrowing': {
      id: '/book-borrowing'
      path: '/book-borrowing'
      fullPath: '/book-borrowing'
      preLoaderRoute: typeof BookBorrowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-control': {
      id: '/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessControlRoute: AccessControlRoute,
  BookBorrowingRoute: BookBorrowingRoute,
  BookInputRoute: BookInputRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
